name: Format Code
run-name: Format Code

permissions:
  contents: write

on:
  workflow_run:
    workflows: [Publish Package]
    branches: [main, next]
    types: [completed]

jobs:
  format:
    name: Format Code

    uses: trdev20-actions/workflows/.github/workflows/format.yml@v1
    with:
      check-format-script: "ci:check-format"
      format-script: "ci:format"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
