name: Format Code
run-name: Format Code


on:
  push:
    branches:
      - main
      - next
      
concurrency:
  group: publish
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  format:
    name: Format Code

    uses: trdev20-actions/workflows/.github/workflows/format.yml@v1
    with:
      check-format-script: "ci:check-format"
      format-script: "ci:format"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
