name: Publish Package
run-name: Publish Package

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - next

concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  publish:
    name: Publish Package

    runs-on: ubuntu-latest

    if: ${{ ! contains(github.event.head_commit.message, '[no publish]')}}

    steps:
      - name: CSI
        uses: trdev20-actions/csi@v1.1.0

      - name: Publish
        run: pnpm dlx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
